### ISSUE TITLE
Generating of src with cdn

### ISSUE THREAD

**Issue by Syedwaheed** [halibegic/hls#2]
Can you please help me with how to generate such src with cdn? I m unable to create such links. Can you please tell me how have you created this link ? any tutorial would be highly helpful for me. Thanks

**Comment by halibegic** [comment]
@Syedwaheed you can create HLS stream using ffmpeg command.
Convert you input (e.g. video.mp4) to multiple bitrates (360p, 480p, 720p...). For more informations please read the tutorial: https://docs.peer5.com/guides/production-ready-hls-vod/.

**Comment by halibegic** [comment]
Example https://github.com/halibegic/hls/tree/master/bbb created using this command [https://pastebin.com/raw/jctc0MJ7](https://pastebin.com/raw/jctc0MJ7)

**Comment by Syedwaheed** [comment]
Thanks you very much @halibegic. i m giving that command to my desire fiile through ffmpeg but it shows error
> [NULL @ 000001dee84bf020] Unable to find a suitable output format for '/'
/: Invalid argument
Following is the image of cmd. Please help me with this i need it asap. Thanks in advance.
![capture](https://user-images.githubusercontent.com/14071753/33770362-176a5096-dc4f-11e7-96ec-daaabace6d38.JPG)

**Comment by Syedwaheed** [comment]
This is the command i m using "https://pastebin.com/raw/sEjgJgnC" . The "gsr.mp4" file is in the ffmpeg bin folder.

**Comment by halibegic** [comment]
Try running commands in this order:

First command
`ffmpeg -hide_banner -y -i gsr.mp4 -vf scale=w=640:h=360:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -c:v h264 -profile:v main -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 4 -strict -2  -b:v 800k -maxrate 856k -bufsize 1200k -b:a 96k -hls_segment_filename gsr/360p_%03d.ts gsr/360p.m3u8`

Second command
`ffmpeg -hide_banner -y -i gsr.mp4 -vf scale=w=842:h=480:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -c:v h264 -profile:v main -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 4 -strict -2 -b:v 1400k -maxrate 1498k -bufsize 2100k -b:a 128k -hls_segment_filename gsr/480p_%03d.ts gsr/480p.m3u8`

Third command
`ffmpeg -hide_banner -y -i gsr.mp4 -vf scale=w=1280:h=720:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -c:v h264 -profile:v main -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 4 -strict -2 -b:v 2800k -maxrate 2996k -bufsize 4200k -b:a 128k -hls_segment_filename gsr/720p_%03d.ts gsr/720p.m3u8`

Fourth command
`ffmpeg -hide_banner -y -i gsr.mp4 -vf scale=w=1920:h=1080:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -c:v h264 -profile:v main -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 4 -strict -2 -b:v 5000k -maxrate 5350k -bufsize 7500k -b:a 192k -hls_segment_filename gsr/1080p_%03d.ts gsr/1080p.m3u8`

Then create the playlist.m3u8, inside gsr directory, with the following:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=800000,RESOLUTION=640x360
360p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1400000,RESOLUTION=842x480
480p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2800000,RESOLUTION=1280x720
720p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,RESOLUTION=1920x1080
1080p.m3u8

**Comment by Syedwaheed** [comment]
Once again Thanks for your quick response. First 4 commands have done successfully and i move to gsr directory with cd from cmd. But playlist.m3u8 is not created and showing the error.Sorry for this as i m not familiar at all with ffmpeg. 
![capture](https://user-images.githubusercontent.com/14071753/33772199-b15cf784-dc55-11e7-9a92-9356d67e22a8.JPG)

**Comment by halibegic** [comment]
No problem. Just download this [https://raw.githubusercontent.com/halibegic/hls/master/bbb/playlist.m3u8](https://raw.githubusercontent.com/halibegic/hls/master/bbb/playlist.m3u8) inside gsr directory and then include "gsr/playlist.m3u8" inside index.html.

**Comment by Syedwaheed** [comment]
Kindly tell me one more thing. Should i have to upload all the files in gsr directory to cpanel? Isnt it take to much space as i have 100 of videos for my application. Thanks man :)

**Comment by Syedwaheed** [comment]
But it would be too good for me if you tell how to run above command through cmd. As i have to convert hundreds of videos like this.

**Comment by Syedwaheed** [comment]
I m able to create the playlist.m3u8. The only issue i m facing now that it is playing the last 15 seconds of the video not the whole video. What wrong with this?

**Comment by Syedwaheed** [comment]
Hi @halibegic 
Following is the m3u8 file code,
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:15
#EXTINF:3.200000,
360p_015.ts
#EXTINF:4.800000,
360p_016.ts
#EXTINF:3.200000,
360p_017.ts
#EXTINF:4.800000,
360p_018.ts
#EXTINF:0.266667,
360p_019.ts
#EXT-X-ENDLIST
` And here is the total .ts video clip,
![capture](https://user-images.githubusercontent.com/14071753/33825969-2f614514-de85-11e7-8c29-8027fd7c48a4.JPG)
I have searched the google and found this command"-hls_list_size 0" should be added in the above command but i dont know exactly where to put in above command. Please help me with this. Really thankful for your help.
